/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthenticationRequest } from './models/authentication-request';
export type { AythenticationResponse } from './models/aythentication-response';
export type { RegistrationRequest } from './models/registration-request';
